### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by SKR301** [SKR301/Maze-Solver#5]

**Comment by SKR301** [comment]
Maybe a website, JS??

**Comment by vitaminncpp** [comment]
Hello

**Comment by vitaminncpp** [comment]
ok but tell me what should i supposed to di with that.

**Comment by SKR301** [comment]
Not many requirements...
just visualize what CLI is doing

1) Random maze 
    - get row and columns from user
    - create a random maze based on that
    - get starting point and end point
    - start button to run the algorithm
    - display the output
